apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: notebook-controller
  app.kubernetes.io/name: notebook-controller
configMapGenerator:
- behavior: merge
  name: parameters
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: kubeflow
patchesStrategicMerge:
- overlays/istio/deployment.yaml
resources:
- overlays/application/application.yaml
