# https://github.com/kfserving/kfserving/blob/bb2d47834710331ca6f07a77cf91bb5f1be6f274/docs/apis/README.md
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  annotations:
    sidecar.istio.io/inject: "true"
  name: max-object-detector
  namespace: will-hearn
spec:
  default:
    predictor:
      custom:
        container:
          name: max-object-detector
          # Needs to be Artifactory or k8scc01covidacr container registry to pull
          image: k8scc01covidacr.azurecr.io/kfserving/max-object-detector:latest
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: "1024Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"
      # When communicating with private registry
      # serviceAccountName: azuresa
